checks:
    javascript: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                    - eslint-run
        coverage:
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
filter:
    excluded_paths:
        - tests/*
